version: '3.8'

services:
  # Aplicaci√≥n Spring Boot
  franchise-api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: franchise-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_R2DBC_URL=r2dbc:mysql://mysql:3306/franchises_db
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - franchise-network
    restart: unless-stopped

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: franchise-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=franchises_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ../applications/app-service/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - franchise-network
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local

networks:
  franchise-network:
    driver: bridge
