services:
  franchise-api:
    image: franchises-api:local
    container_name: franchise-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: host.docker.internal
      DB_PORT: 3307
      DB_NAME: franchises_db
      DB_USERNAME: admin
      DB_PASSWORD: ChangeThisPassword123!
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
